TITLE_1: DPG5011
TITLE_2: Formação do Cientista Empreendedor
SUBTITLE_1: Disciplina de pós-graduação
SUBTITLE_2: Material de aula, notebooks e referências.

ABOUT: |
  Este site organiza as aulas, exercícios e material suplementar da disciplina.

REFERENCIAS: |
  <ul>
    <li>Livro A …</li>
    <li>Artigo B …</li>
  </ul>

GITHUB_LINK: https://github.com/Academic-Codex/DPG5011-Formacao-Do-Cientista-Empreendedor
HERO_FILE: cientista-empreendedor-i.png